In [6]:
chr1

,#chr,pos(1-based),ref,alt,aaref,aaalt,hg19_chr,hg19_pos(1-based),Ensembl_transcriptid,MetaRNN_score
0,1,65565,A,C,M,L,1,65565,ENST00000641515,0.3169853
1,1,65565,A,G,M,V,1,65565,ENST00000641515,0.3184599
2,1,65565,A,T,M,L,1,65565,ENST00000641515,0.31631923
3,1,65566,T,A,M,K,1,65566,ENST00000641515,0.34342164
4,1,65566,T,C,M,T,1,65566,ENST00000641515,0.34620103
...,...,...,...,...,...,...,...,...,...,...
8538787,1,248918362,G,C,X,S,1,249212561,ENST00000355360;ENST00000329291,0.46256214;0.46256214
8538788,1,248918362,G,T,X,L,1,249212561,ENST00000355360;ENST00000329291,0.46433994;0.46433994
8538789,1,248918363,A,C,X,C,1,249212562,ENST00000355360;ENST00000329291,0.4693281;0.4693281
8538790,1,248918363,A,G,X,W,1,249212562,ENST00000355360;ENST00000329291,0.46355912;0.46355912
8538791,1,248918363,A,T,X,C,1,249212562,ENST00000355360;ENST00000329291,0.4750286;0.4750286